# Generated by Django 2.1 on 2019-06-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='math_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maths.Maths'),
        ),
    ]
